import Head from 'next/head';
import Header from '../Header';

const Main = ({ children }) => {
  return (
    <main>
      <Head>
        <title>Fasrevo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header></Header>
      {children}
    </main>
  );
};

export default Main;
