import React, { useState } from 'react';
import { useRouter } from 'next/router';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import Input from '../../../src/components/Input/index.js';
import Button from '../../../src/components/Button/index.js';
import Head from 'next/head.js';

const SignIn = () => {
  const [message, setMessage] = useState();
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const handleSubmit = async (values) => {
    try {
      setLoading(true);
      // await axios.post(`${login}`, values).then((resp) => {
      //   dispatch(setAuthenticated(resp.data.authenticated));
      // });
    } catch ({ response }) {
      if (response.data.status === 0) {
        setMessage(response.data.message);
      } else {
        router.push('/');
      }
    } finally {
      setLoading(false);
    }
  };

  const formik = useFormik({
    initialValues: {
      email: '',
      password: '',
    },
    validationSchema: Yup.object({
      email: Yup.string()
        .email('Email không hợp lệ')
        .required('Email không được để trống'),
      password: Yup.string().required('Mật khẩu không được để trống'),
    }),
    onSubmit: (values) => {
      handleSubmit(values);
    },
  });

  return (
    <div className='w-full container mx-auto min-h-screen max-h-[850px] flex justify-center items-center'>
      <Head>
        <title>Đăng nhập</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='px-5 py-10 w-full max-w-[500px] text-primary'>
        <h1 className='font-bold text-center text-2xl pt-5 pb-6'>Đăng nhập</h1>
        <p className='text-base text-center pb-3 text-primary'>
          Chào mừng đến với Fasrevo
        </p>
        <form onSubmit={formik.handleSubmit}>
          <Input
            type='email'
            name='email'
            label='Tài khoản'
            placeholder='Nhập tài khoản*'
            onChange={formik.handleChange}
            value={formik.values.email}
            touched={formik.touched.email}
            error={formik.errors.email}
          />
          <Input
            type='password'
            name='password'
            label='Mật khẩu'
            placeholder='Nhập mật khẩu*'
            onChange={formik.handleChange}
            value={formik.values.password}
            touched={formik.touched.password}
            error={formik.errors.password}
          />
          {message ? (
            <div className='text-secondary_red bg-[#ffe2e2] h-10 text-center text-sm mb-5 font-medium flex items-center justify-center'>
              {message}
            </div>
          ) : null}
          <Button type='submit' loading={loading}>
            Đăng nhập
          </Button>
        </form>
      </div>
    </div>
  );
};

export default SignIn;
