import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import Button from '../../src/components/Button';

const Receipt = () => {
  return (
    <div className='w-full min-h-screen flex justify-center items-center'>
      <Head>
        <title>Thanh toán thành công</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='px-5 py-10 w-full max-w-[550px] text-primary text-center flex flex-col items-center'>
        <div className='rounded-full w-20 h-20 bg-green-600 flex justify-center items-center text-white'>
          <svg
            xmlns='http://www.w3.org/2000/svg'
            fill='none'
            viewBox='0 0 24 24'
            strokeWidth={1.5}
            stroke='currentColor'
            className='w-10 h-10'
          >
            <path
              strokeLinecap='round'
              strokeLinejoin='round'
              d='M4.5 12.75l6 6 9-13.5'
            />
          </svg>
        </div>
        <h1 className='mt-5 text-2xl font-bold'>Thanh toán thành công</h1>
        <p className='py-3'>
          Giao dịch được thực hiện thành công. Cảm ơn quý khách đã sử dụng dịch
          vụ
        </p>
        <p className='pb-3'>Bạn đã thanh toán 249.000 VND</p>
        <div className='w-full gap-x-5 flex justify-center items-center'>
          <Button fullWidth={false}>
            <Link href={'/'}>
              <a>Lịch sử mua hàng</a>
            </Link>
          </Button>
          <Button fullWidth={false}>
            <Link href={'/'}>
              <a>Trở về trang chủ</a>
            </Link>
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Receipt;
